language: node_js
node_js:
  - "10"
script:
  - npm run test
deploy:
  provider: npm
  access: public
  skip_cleanup: true
  email: greenrenge@gmail.com
  api_key:
    secure: dI36V9yLvpbq8gujc+StijVYrf28QB7A3/AMA25xjBT+mxs04vcEoYV+EsG5I1rrxudA49L37WSnThii4Eh7H3iunNDUYbqqHEqkgOxeNKKulrK5arsfKbsSe00Wwtkx4z8DetxINgaBdH6CSg1WXMDn2yW6E2U0iw7Ev82RpFcFQkoqqp75GIb5ZAaQ9r0JC3Md8dTGDQg3RfBpGunEm06axNsJi7emLrMFs8MduZOIEluR57nKsOp0TRwn92g5KdoGw2s6Cb/LC9n4LN/wYJgZrPz2sUJeAXRW7+EOWhBt8RlltQUEmAuyhO2YWrFmWIo56zR/vi7Ktyziz8zjywmcR3POLGxHZ064TN5Bho5ROkekE3zLsrw8K2uav6fTDD4gB8gkycTmCIaX5Y9I3sadwMBKU9hHdVXzbzwxyRWB/omru0wFOx/TqiBYUrfyj5Bb7OJrPlaN7bVghHsKyoK5u+RDuBFOqi4dRVkJ1kcGqKnUzPKWv12poyldQEKQN0TlxGWWTCa9er+xxeCkSbxrIvwXov2MwvFc+H4EtpmKF8HL94Hp+Ifyy3YGZRX4wrE2ZQdr+WwzmA1OQOI7TSlWa2HPt8atGipAB8kVj6OBNQFWWSCsoqjEdtN/5ACMQ+qVcwxK38ju5YUAx59s1yDi+fuB9kJn4K2MFM2oM7Q=
  on:
    tags: true
